### ISSUE TITLE
Команда AddTranslation

### ISSUE THREAD

**Issue by Nafanyan** [d3nari/Travelline2024#4]
При выполнении команды AddTranslation программа просит путь файла, какого файла, зачем этот файл обычному пользователю непонятно.
![image](https://github.com/d3nari/travelline_practice/assets/90004716/c7b7b90b-a09b-4cea-9e18-3f2aeba16e3e)

При вводе существующего файла выводится информация что файл удачно считан и всё, а как добавить новый перевод?
![image](https://github.com/d3nari/travelline_practice/assets/90004716/bc1466ef-7c95-45cb-b2b7-147a24a85630)

Либо может я чего-то не понимаю)

**Comment by d3nari** [comment]
Я могу отвечать сюда?
Просто в дополнительном задании было сказано сделать ввод из файла вместо
всех остальных команд и я так понял, что пользователь редактирует файл и
загружает заново его, чтобы внести изменения

чт, 21 мар. 2024 г., 08:42 Nafanya ***@***.***>:

**Comment by Nafanyan** [comment]
Да, можешь)

А слушай и правда, хм, соре, зря быканул)

**Comment by Nafanyan** [comment]
Хм, может тогда

**Comment by d3nari** [comment]
Хорошо, спасибо за ревью кода)

чт, 21 мар. 2024 г., 09:05 Nafanya ***@***.***>:
